module.exports = {
  and: require('./and'),
  compose: require('./compose'),
  copy: require('./copy'),
  debounce: require('./debounce'),
  findWhere: require('./findWhere'),
  get: require('./get'),
  isDeepEqual: require('./isDeepEqual'),
  isEqual: require('./isEqual'),
  literal: require('./literal'),
  merge: require('./merge'),
  not: require('./not'),
  or: require('./or'),
  pop: require('./pop'),
  push: require('./push'),
  set: require('./set'),
  shift: require('./shift'),
  toggle: require('./toggle'),
  unset: require('./unset'),
  unshift: require('./unshift'),
  when: require('./when')
}
